exports.avatarCPUSample = {
  accessories: ["wayfarers"],
  accessoriesColor: ["a7ffc4"],
  accessoriesProbability: 100,
  backgroundColor: ["65c9ff"],
  backgroundType: ["solid"],
  clothesColor: ["3c4f5c"],
  clothing: ["hoodie"],
  clothingGraphic: [null],
  eyebrows: ["raisedExcitedNatural"],
  eyes: ["hearts"],
  facialHair: ["beardLight"],
  facialHairColor: ["2c1b18"],
  facialHairProbability: 100,
  hairColor: ["4a312c"],
  hatColor: ["e6e6e6"],
  mouth: ["sad"],
  size: 64,
  skinColor: ["ffdbb4"],
  top: ["shortWaved"],
  topProbability: 100,
};
